### PR TITLE
Update links for icon and font designers

### LINKED ISSUE #19: [bug] Footer links for Icon and Font designer are out of date
**Describe the bug**

Footer links for Icon and Font creator no longer link to pages that work.

**Steps to Reproduce**

Click the link for Martin Bérubé and notice you get a permission denied error.

Click the link for  Vernon Adams and you are taken to a Google Plus page explaining the G+ is no longer a thing.

**Expected behavior**

Links take me to a page relevant to the artists.

A quick check shows Martin's web profiles point to https://www.how-to-draw-funny-cartoons.com/ as their homepage.

Vernon has since passed away in 2016 and the most official looking place I could find was their GitHub page at https://github.com/vernnobile

### PR DESCRIPTION
**Pull request by arusso**
Updates footer links for icon and font designers to working pages.

Resolves #19

### CODE REVIEW

**Review by ramses0 — APPROVED** [review]
<deleted>

**Comment by coreydaley** [comment]
The https://www.how-to-draw-funny-cartoons.com url keeps blocking me, is it still correct?

**Comment by arusso** [comment]
I am seeing the same thing. I suspect the domain has lapsed since I submitted the PR and it's parked/squatted since it redirects to sitesell [dot] com.

Quick search doesn't give me any obvious alternative.

**Comment by coreydaley** [comment]
Closing as obsolete

**Pull request closed without merging**
